apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosmos-client-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  cosmos-client-pod
  template:
    metadata:
      labels:
        app: cosmos-client-pod
    spec:
      containers:
      - name: main
        image: vplauzon/perf-streaming:experimental
        imagePullPolicy: Always
        env:
        - name: MODE
          value: "cosmos-client"
        - name: APP_INSIGHTS_KEY
          value: "{app-insights-key}"
        - name: CONCURRENT_CALL_COUNT
          value: "1"
        resources:
          requests:
            memory: "512M"
            cpu: "1200m"
          limits:
            memory: "5G"
            cpu: "2"
